### ISSUE TITLE
Fix for broken menu

### ISSUE THREAD

**Issue by electroglyph** [InspectorCaracal/evelite-client#3]
Characters/Channels links in menu are broken. but adding `\templates\website\base.html` from Evennia fixes it

**Comment by InspectorCaracal** [comment]
This kind of side effect when using evennia's templates shouldn't be happening at all, so I'm investigating it as a core evennia issue. I'll leave this open until I have some kind of resolution for it.

**Comment by InspectorCaracal** [comment]
Resolved by https://github.com/evennia/evennia/pull/3566
